# Generated by Django 5.1 on 2024-08-14 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='imagem',
        ),
    ]
